directories:
  stored_csv_xlsx_directory: data/csv_xlsx
  sqldb_directory: data/sqldb.db
  uploaded_files_sqldb_directory: data/uploaded_files_sqldb.db
  stored_csv_xlsx_sqldb_directory: data/csv_xlsx_sqldb.db
  persist_directory: data/chroma

llm_config:
    agent_llm_system_role: |
      Given the following user question, corresponding SQL query, and SQL result, answer the user question.
      Question: {question}
      SQL Query: {query}
      SQL Result: {result}
      Answer:
    rag_llm_system_role: |
      You will receive the user's question along with the search results of that question over a database. Provide the user with the proper answer.
    engine: "llama-3.1-70b-versatile"
    temperature: 0.1

rag_config:
  collection_name: titanic_small
  top_k: 1